# TCL File Generated by Component Editor 18.1
# Mon Feb 11 16:20:55 BRST 2019
# DO NOT MODIFY


# 
# arbitro "arbitro" v1.0
#  2019.02.11.16:20:55
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module arbitro
# 
set_module_property DESCRIPTION ""
set_module_property NAME arbitro
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME arbitro
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL arbitro
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file clock_Counter.v VERILOG PATH clock_Counter.v
add_fileset_file arbitro.v VERILOG PATH ../arbitro/arbitro.v TOP_LEVEL_FILE
add_fileset_file uart_rx.v VERILOG PATH ../arbitro/uart_rx.v
add_fileset_file uart_tx.v VERILOG PATH ../arbitro/uart_tx.v


# 
# parameters
# 
add_parameter IDLE STD_LOGIC_VECTOR 0
set_parameter_property IDLE DEFAULT_VALUE 0
set_parameter_property IDLE DISPLAY_NAME IDLE
set_parameter_property IDLE TYPE STD_LOGIC_VECTOR
set_parameter_property IDLE UNITS None
set_parameter_property IDLE ALLOWED_RANGES 0:15
set_parameter_property IDLE HDL_PARAMETER true
add_parameter REQUEST STD_LOGIC_VECTOR 1
set_parameter_property REQUEST DEFAULT_VALUE 1
set_parameter_property REQUEST DISPLAY_NAME REQUEST
set_parameter_property REQUEST TYPE STD_LOGIC_VECTOR
set_parameter_property REQUEST UNITS None
set_parameter_property REQUEST ALLOWED_RANGES 0:15
set_parameter_property REQUEST HDL_PARAMETER true
add_parameter ANSWER_TIME STD_LOGIC_VECTOR 2
set_parameter_property ANSWER_TIME DEFAULT_VALUE 2
set_parameter_property ANSWER_TIME DISPLAY_NAME ANSWER_TIME
set_parameter_property ANSWER_TIME TYPE STD_LOGIC_VECTOR
set_parameter_property ANSWER_TIME UNITS None
set_parameter_property ANSWER_TIME ALLOWED_RANGES 0:15
set_parameter_property ANSWER_TIME HDL_PARAMETER true
add_parameter TIMEOUT STD_LOGIC_VECTOR 3
set_parameter_property TIMEOUT DEFAULT_VALUE 3
set_parameter_property TIMEOUT DISPLAY_NAME TIMEOUT
set_parameter_property TIMEOUT TYPE STD_LOGIC_VECTOR
set_parameter_property TIMEOUT UNITS None
set_parameter_property TIMEOUT ALLOWED_RANGES 0:15
set_parameter_property TIMEOUT HDL_PARAMETER true
add_parameter CHECKSUM STD_LOGIC_VECTOR 4
set_parameter_property CHECKSUM DEFAULT_VALUE 4
set_parameter_property CHECKSUM DISPLAY_NAME CHECKSUM
set_parameter_property CHECKSUM TYPE STD_LOGIC_VECTOR
set_parameter_property CHECKSUM UNITS None
set_parameter_property CHECKSUM ALLOWED_RANGES 0:15
set_parameter_property CHECKSUM HDL_PARAMETER true
add_parameter SEND_BACK STD_LOGIC_VECTOR 5
set_parameter_property SEND_BACK DEFAULT_VALUE 5
set_parameter_property SEND_BACK DISPLAY_NAME SEND_BACK
set_parameter_property SEND_BACK TYPE STD_LOGIC_VECTOR
set_parameter_property SEND_BACK UNITS None
set_parameter_property SEND_BACK ALLOWED_RANGES 0:15
set_parameter_property SEND_BACK HDL_PARAMETER true
add_parameter TRYALARM STD_LOGIC_VECTOR 6
set_parameter_property TRYALARM DEFAULT_VALUE 6
set_parameter_property TRYALARM DISPLAY_NAME TRYALARM
set_parameter_property TRYALARM TYPE STD_LOGIC_VECTOR
set_parameter_property TRYALARM UNITS None
set_parameter_property TRYALARM ALLOWED_RANGES 0:31
set_parameter_property TRYALARM HDL_PARAMETER true
add_parameter c_CLOCK_PERIOD_NS INTEGER 100
set_parameter_property c_CLOCK_PERIOD_NS DEFAULT_VALUE 100
set_parameter_property c_CLOCK_PERIOD_NS DISPLAY_NAME c_CLOCK_PERIOD_NS
set_parameter_property c_CLOCK_PERIOD_NS TYPE INTEGER
set_parameter_property c_CLOCK_PERIOD_NS UNITS None
set_parameter_property c_CLOCK_PERIOD_NS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property c_CLOCK_PERIOD_NS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave clock clk Input 1
add_interface_port nios_custom_instruction_slave reset reset Input 1
add_interface_port nios_custom_instruction_slave clock_en clk_en Input 1
add_interface_port nios_custom_instruction_slave dataA dataa Input 32
add_interface_port nios_custom_instruction_slave done done Output 1
add_interface_port nios_custom_instruction_slave result result Output 32


# 
# connection point tx
# 
add_interface tx conduit end
set_interface_property tx associatedClock ""
set_interface_property tx associatedReset ""
set_interface_property tx ENABLED true
set_interface_property tx EXPORT_OF ""
set_interface_property tx PORT_NAME_MAP ""
set_interface_property tx CMSIS_SVD_VARIABLES ""
set_interface_property tx SVD_ADDRESS_GROUP ""

add_interface_port tx tx writeresponsevalid_n Output 1

