// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon Feb 11 16:25:49 2019

arbitro arbitro_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.reset(reset_sig) ,	// input  reset_sig
	.clock_en(clock_en_sig) ,	// input  clock_en_sig
	.dataA(dataA_sig) ,	// input [31:0] dataA_sig
	.tx(tx_sig) ,	// output  tx_sig
	.done(done_sig) ,	// output  done_sig
	.result(result_sig) 	// output [31:0] result_sig
);

defparam arbitro_inst.IDLE = 'b000;
defparam arbitro_inst.REQUEST = 'b001;
defparam arbitro_inst.ANSWER_TIME = 'b010;
defparam arbitro_inst.TIMEOUT = 'b011;
defparam arbitro_inst.CHECKSUM = 'b100;
defparam arbitro_inst.SEND_BACK = 'b101;
defparam arbitro_inst.TRYALARM = 'b0110;
defparam arbitro_inst.c_CLOCK_PERIOD_NS = 100;
