// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Thu Feb 07 10:05:58 2019

uart_tx uart_tx_inst
(
	.CLKS_PER_BIT(CLKS_PER_BIT_sig) ,	// input  CLKS_PER_BIT_sig
	.i_Clock(i_Clock_sig) ,	// input  i_Clock_sig
	.i_Tx_DV(i_Tx_DV_sig) ,	// input  i_Tx_DV_sig
	.i_Tx_Byte(i_Tx_Byte_sig) ,	// input [7:0] i_Tx_Byte_sig
	.o_Tx_Active(o_Tx_Active_sig) ,	// output  o_Tx_Active_sig
	.o_Tx_Serial(o_Tx_Serial_sig) ,	// output  o_Tx_Serial_sig
	.o_Tx_Done(o_Tx_Done_sig) 	// output  o_Tx_Done_sig
);

defparam uart_tx_inst.s_IDLE = 'b000;
defparam uart_tx_inst.s_TX_START_BIT = 'b001;
defparam uart_tx_inst.s_TX_DATA_BITS = 'b010;
defparam uart_tx_inst.s_TX_STOP_BIT = 'b011;
defparam uart_tx_inst.s_CLEANUP = 'b100;
